### ISSUE TITLE
ix downloads fail for IMG USGS files

### ISSUE THREAD

**Issue by curtiss9** [MillionConcepts/pdr-tests#6]
`ix index` and `ix download` fail for IMG USGS products. Files can be downloaded via `ix index` if the domain field in the _subset.csv is manually replaced by the obfuscated cloudfront.net address, but the downloads fail when using the stable bucket name/address. `ix download` then runs successfully without further edits needed.

To test `ix download` alone, I replaced the cloudfront.net address in the url_stem field of the cassini_iss calib_da index with the cassini bucket url (to replicate what the index would be if `ix index` had successfully run without the above manual edits). `ix download` failed with this "unmodified" calib_da_.csv index in the same way `ix index` did with an unmodified calib_da_subset.csv sample list.

Note: the cassini_iss calib_da_test.csv index pushed to main on 9/20 uses the obfuscated cloudfront address in its url_stem field.

**Comment by m-stclair** [comment]
changes [here](https://github.com/MillionConcepts/pdr-tests/tree/ix_s3_compat) should hopefully allow ix dial-out commands to work smoothly with objects on S3. please test.

**Comment by m-stclair** [comment]
merged and resolved.
